import { CardsType } from './components/interfaces';

export const emptyState = { items: [], selectedItem: null };
export const mockResponse: CardsType = [
  {
    id: '8912830912830',
    title: "Someone's birthday",
    day: '27',
    month: 'Jun',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '367234548682348',
    title: '2nd meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '367345345248682348',
    title: '3rd meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '3245345',
    title: '4th meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '3245345345',
    title: 'safd meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '3453452345',
    title: 'dfdf meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '2345345',
    title: 'ewrw meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '34534523',
    title: 'xcv meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '345324532',
    title: 'sdfs meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '435245',
    title: 'xcv meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
  {
    id: '36724868',
    title: 'wer meeting with X',
    day: '14',
    month: 'May',
    year: '2020',
    dateString: '',
    editMode: false,
  },
];
export const DEFAULT_TIME = '23:59:59';

export const YEARS_LIST = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
